### ISSUE TITLE
Detail on readme

### ISSUE THREAD

**Issue by MatheusKProt** [Rocketseat/adonis-acl#3]
Hi!

In the installation item 6 on readme has this line: 
Publish the package migrations to your application and run these with `adonis migrations:run`.

The right command is `adonis migration:run`

**Comment by jpdemagalhaes** [comment]
Hey @MatheusKProt thanks for the submission.

No need to close this since you're actually right!

I'll make a PR to fix this ❤️

**Comment by jpdemagalhaes** [comment]
Done on #4
